# Generated by Django 2.1.5 on 2020-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='summary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
